"""
Helper functions for data synthesis.
"""

import numpy as np
import numpy as np
import copy
import figs.utilities.trajectory_helper as th

from typing import Dict,Union,List

def generate_frames(Tsps:np.ndarray,
                    base_frame_config:Dict[str,Union[int,float,List[float]]],
                    parameters_bounds:List[float],
                    rng_seed:Union[int,None]=None) -> List[Dict[str,Union[np.ndarray,str,int,float]]]:
    
    """
    Generates a list of drone variations for a given base drone configuration. The configurations are
    generated by perturbing the base drone configuration with bounded uniform noise. The number of
    configurations generated is determined by the sample set config dictionary.

    Args:
        Tsps:               Sample times.
        base_frame_config:  Base frame configuration dictionary.
        parameters_bounds:  Frame sample set config dictionary.
        rng_seed:           Random number generator seed.

    Returns:
        Drones:             List of drone configurations (dictionary format).
    """

    # TODO: Generalize this to nnio config
    parameters_key = ["mass","force_normalized"]

    # Sample Count
    Nsps = len(Tsps)

    # Set random number generator seed
    if rng_seed is not None:
        np.random.seed(rng_seed)

    # Generate Drone Frames
    Frames = []
    for _ in range(Nsps):
        # Instantiate a new frame
        frame = copy.deepcopy(base_frame_config)

        # Randomize the frame
        for idx,key in enumerate(parameters_key):
            bounds = [-parameters_bounds[idx],parameters_bounds[idx]]
            frame[key] += np.random.uniform(*bounds)

        # Save to a dictionary
        Frames.append(frame)

    return Frames

def generate_perturbations(Tsps:np.ndarray,
                           Tpd:np.ndarray,CPd:np.ndarray,
                           initial_bounds:List[float],
                           rng_seed:int=None) -> List[Dict[str,Union[float,np.ndarray]]]:
    """
    Generates a list of perturbed initial states for the drone given an ideal trajectory. The perturbed
    initial states are generated by sampling a random initial times and corresponding state vectors from
    the ideal trajectory using a bounded uniform distribution. The state vectors are then perturbed with
    uniform noise. The number of perturbed initial states generated is determined by the sample set
    config dictionary.

    Args:
        Tsps:                   Sample times.
        Tpd:                    Ideal trajectory times.
        CPd:                    Ideal trajectory control points.
        initial_bounds:         Initial state bounds.
        rng_seed:               Random number generator seed.

    Returns:
        Perturbations:          List of perturbations (dictionary format).
    """

    # Sample Count
    Nsps = len(Tsps)

    # Set random number generator seed
    if rng_seed is not None:
        np.random.seed(rng_seed)
    
    # Unpack the config
    w_x0 = np.array(initial_bounds,dtype=float)

    # Get ideal trajectory for quaternion checking
    tXUd = th.TS_to_tXU(Tpd,CPd,None,10)

    # Generate perturbed starting points    
    Perturbations = []
    for i in range(Nsps):
        # Sample random start time and get corresponding state vector sample
        t0 = Tsps[i]
        idx0 = np.where(Tpd <= t0)[0][-1]
        idx0 = min(idx0,(len(Tpd)-2))
        t00,t0f = Tpd[idx0],Tpd[idx0 + 1]

        x0s = th.ts_to_xu(t0-t00,t0f-t00,CPd[idx0,:,:],None)
        
        # Perturb state vector sample
        w0 = np.random.uniform(-w_x0,w_x0)
        x0 = x0s + w0
        
        # Ensure quaternion is well-behaved (magnitude and closest to previous)
        idxr = np.where(tXUd[0,:] <= t0)[0][-1]
        x0[6:10] = th.obedient_quaternion(x0[6:10],tXUd[7:11,idxr])

        # Store perturbation in list
        perturbation = {"t0":t0,"x0":x0}
        Perturbations.append(perturbation)
    
    return Perturbations

def compute_Tsp_batches(t0:float,tf:float,dt_ro:Union[None,float],
                        rate:Union[None,int],reps:Union[None,int],Nro_ds:int=None,
                        shuffle:bool=True) -> List[np.ndarray]:
    """
    Compute the sample start times for a given rollout.

    Args:
        t0:     Start time of the trajectory.
        tf:     End time of the trajectory.
        dt_ro:  Sample time for each rollout.
        rate:   Number of time points per second.
        reps:   Number of rollouts per time point.
        Nro_ds: Number of rollouts per dataset.

    Returns:
        Tsp_bts:    Array containing batches of sampled start times.

    """
    
    # Compute the trajectory duration
    dt_tt = tf - t0                                            # Total trajectory duration
    
    # Catch None value cases
    dt_ro = dt_ro or dt_tt
    rate = rate or 1/dt_ro
    reps = reps or 1

    # Compute sample start times and batchify
    Ntp = int(rate*dt_tt)                                       # Number of time points per trajectory
    Nsp = int(reps*Ntp)                                         # Number of sample points (total)

    # Compute the sample points array
    if dt_ro == dt_tt:
        Tsp = np.array([t0]*Nsp)                                # Entire sample points array
    else:
        Tsp = np.tile(np.linspace(t0,tf,Ntp+1)[:-1],reps)     # Entire sample points array
        Tsp += np.random.uniform(-1/rate,1/rate,Nsp)        # Add some noise to the sample points array
        Tsp = np.clip(Tsp,t0,tf)                                # Clip the sample points array

    # Shuffle if required
    if shuffle:
        np.random.shuffle(Tsp)

    # Split into batches of datasets
    if Nro_ds is not None:
        Tsp_bts = np.split(Tsp,np.arange(Nro_ds,Nsp,Nro_ds))        # Split the sample points array into their batches
    else:
        Tsp_bts = [Tsp]                                             # No batching, return the entire array as a single batch
    
    return Tsp_bts